# Generated by Django 5.0.7 on 2024-08-09 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=140)),
                ('starting_bid', models.IntegerField()),
                ('current_bid', models.IntegerField()),
                ('url', models.URLField()),
                ('category', models.CharField(max_length=64)),
                ('bid_count', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
